/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./src/components/common/Scroll/BetterScroll.vue')['default']
    ItemTitle: typeof import('./src/components/content/ItemTitle/ItemTitle.vue')['default']
    ListItem: typeof import('./src/components/content/ListItem/ListItem.vue')['default']
    Lyric: typeof import('./src/components/content/Lyric/Lyric.vue')['default']
    Mainbar: typeof import('./src/components/content/MainBar/Mainbar.vue')['default']
    MusicItem: typeof import('./src/components/content/MusicItem/MusicItem.vue')['default']
    NavBar: typeof import('./src/components/common/NavBar/NavBar.vue')['default']
    PlayBar: typeof import('./src/components/content/PlayBar/PlayBar.vue')['default']
    PlayBg: typeof import('./src/components/content/Play/PlayBg.vue')['default']
    PlayCover: typeof import('./src/components/content/Play/PlayCover.vue')['default']
    PlayList: typeof import('./src/components/content/PlayList/PlayList.vue')['default']
    PlayNav: typeof import('./src/components/content/Play/PlayNav.vue')['default']
    PlayProgressBar: typeof import('./src/components/content/Play/PlayProgressBar.vue')['default']
    PlayVolume: typeof import('./src/components/content/Play/PlayVolume.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/common/Scroll/Scroll.vue')['default']
    TabBar: typeof import('./src/components/common/TabBar/TabBar.vue')['default']
    TabBarItem: typeof import('./src/components/common/TabBar/TabBarItem.vue')['default']
    VanLoading: typeof import('vant/es')['Loading']
  }
}
